export const productData = [
  {
    id: 1,
    picture: "/assets/aerox.png",
    name: "Yamaha Aerox 2023",
    location: "Kolkata",
    resalePrice: 82000,
    originalPrice: 174000,
    usage: "1 Year",
    postedOn: "04-11-2024",
    seller: "Aero",
    verified: true
  },
  {
    id: 2,
    picture: "/assets/activa.png",
    name: "Honda Activa 2022",
    location: "Kolkata",
    resalePrice: 45000,
    originalPrice: 110000,
    usage: "2 Years",
    postedOn: "04-11-2024",
    seller: "Acti",
    verified: true,
  },
  {
    id: 3,
    picture: "/assets/burgman.png",
    name: "Suzuki Burgman 2022",
    location: "Kolkata",
    resalePrice: 75000,
    originalPrice: 145000,
    usage: "3 Years",
    postedOn: "04-11-2024",
    seller: "Burg",
    verified: false,
  },
  {
    id: 4,
    picture: "/assets/bed.png",
    name: "Queen-Double-Bed",
    location: "Kolkata",
    resalePrice: 32000,
    originalPrice: 58000,
    usage: "5 Years",
    postedOn: "04-11-2024",
    seller: "Bedi",
    verified: false,
  },
  {
    id: 5,
    picture: "/assets/dining.png",
    name: "Dining-Table",
    location: "Kolkata",
    resalePrice: 25000,
    originalPrice: 70000,
    usage: "6 Years",
    postedOn: "04-11-2024",
    seller: "Dini",
    verified: true,
  },
  {
    id: 6,
    picture: "/assets/sofa.png",
    name: "Sofaset",
    location: "Kolkata",
    resalePrice: 60000,
    originalPrice: 150000,
    usage: "4 Years",
    postedOn: "04-11-2024",
    seller: "Sofi",
    verified: true,
  },
  {
    id: 7,
    picture: "/assets/samsung.png",
    name: "500L Refrigerator",
    location: "Kolkata",
    resalePrice: 30000,
    originalPrice: 90000,
    usage: "4 Years",
    postedOn: "04-11-2024",
    seller: "Sams",
    verified: true,
  },
  {
    id: 8,
    picture: "/assets/lg.png",
    name: "6Kg Washing Machine",
    location: "Kolkata",
    resalePrice: 45000,
    originalPrice: 15000,
    usage: "5 Years",
    postedOn: "04-11-2024",
    seller: "Elgu",
    verified: false,
  },
  {
    id: 9,
    picture: "/assets/ifb.png",
    name: "3L Micro Woven",
    location: "Kolkata",
    resalePrice: 30000,
    originalPrice: 12000,
    usage: "2 Years",
    postedOn: "04-11-2024",
    seller: "Indu",
    verified: true,
  },
]